[env:nano]
platform  = atmelavr
board     = nanoatmega328new
framework = arduino

monitor_speed = 115200

lib_deps =
  majicDesigns/MD AD9833
  etherkit/Si5351Arduino
  etherkit/JTEncode
  mikalhart/TinyGPS
