[env]
monitor_speed = 115200

lib_deps =
  etherkit/Etherkit JTEncode@^1.3.1

build_flags =
  -DCALIBRATION=67760

[env:nano]
platform      = atmelavr
board         = nanoatmega328
framework     = arduino
upload_speed  = 57600

[env:nano_new]
platform      = atmelavr
board         = nanoatmega328new
framework     = arduino
upload_speed  = 115200
